title: Vida Adeli
logo: /assets/img/logo.png
description: "PhD Candidate | Computer Science<br>University of Toronto<br>Computer Vision Researcher"
show_downloads: false
# google_analytics: UA-XXXXXX-X  # Add your Google Analytics tracking ID here if needed
theme: jekyll-theme-minimal
