title: Vida Adeli - AI/ML Researcher
logo: /assets/img/logo.png
description: PhD Candidate | University of Toronto
show_downloads: false
# google_analytics: UA-XXXXXX-X  # Add your Google Analytics tracking ID here if needed
theme: jekyll-theme-minimal
